server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Minimum 32+ chars for HS256 key
app.jwt.secret=MyVerySecretJwtKeyForHomeworkProject123456
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

# springdoc
springdoc.swagger-ui.path=/swagger-ui.html
