server.port=8080

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Minimum 32+ chars for HS256 key
app.jwt.secret=MyVerySecretJwtKeyForHomeworkProject123456
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
